parserOptions:
  sourceType: 'module'
  ecmaVersion: 2017

plugins:
  - markdown

env:
  es6: true
  browser: true
  mocha: true

extends: 'htmlacademy/es6'

rules:
  no-undef: off
  no-unused-vars: off
  no-console: off
  no-invalid-this: off
  curly: off
  no-unreachable: off
  eqeqeq: off
  no-unused-expressions: off
  no-constant-condition: off
  no-trailing-spaces: off
