lang: "ru"

githubUrl: "https://github.com/htmlacademy/intensive-ecmascript-criteria"
issuesUrl: "https://github.com/htmlacademy/intensive-ecmascript-criteria/issues"
pullsUrl: "https://github.com/htmlacademy/intensive-ecmascript-criteria/pulls"

theme: minima
